# Generated by Django 5.1.4 on 2025-05-27 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0004_exam_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='marks',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
