# Generated by Django 5.1.4 on 2025-05-27 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0005_exam_marks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='marks',
        ),
        migrations.AddField(
            model_name='question',
            name='marks',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
