# Generated by Django 5.1.4 on 2025-05-29 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0007_exam_duration_minutes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='duration_minutes',
        ),
    ]
