# Generated by Django 5.1.4 on 2025-05-29 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0008_remove_exam_duration_minutes'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='duration_minutes',
            field=models.PositiveIntegerField(default=5),
        ),
    ]
