# Generated by Django 5.1.4 on 2025-09-14 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0011_teacherprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherprofile',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
